### ISSUE TITLE
Need react version update

### ISSUE THREAD

**Issue by pralivera** [exelban/react-image-crop-component#6]
I was tried to use this package and got following error.

Element ref was specified as a string (RICC_main_container) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.
▶ 29 stack frames were collapsed.
./src/index.js
F:/GIT/PBIC/Designer_Tool_Sprint_2/designer_web/src/index.js:15
  12 | 
  13 | 
  14 | const store = configureStore();
> 15 | ReactDOM.render(
  16 |   <Provider store={store}>
  17 |     <App />
  18 |   </Provider>,
View compiled
▶ 6 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

Then I went through the your code and identified you use react 15.6.2 and my version is 16.3.2. So it seems your package load react 15.6.2 and due to that this issue will happened.

So is it possible to update react version of this package. Thank you ..

**Comment by exelban** [comment]
Thanks.
I will update library next week.
