### ISSUE TITLE
Error on cropping

### ISSUE THREAD

**Issue by Varshazz** [exelban/react-image-crop-component#9]
I see this error on cropping hence the callback function doesn't get called
_

> Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

_

**Comment by Varshazz** [comment]
Anyone looking into this ?

**Comment by exelban** [comment]
@Varshazz can you give the code which reproducing error on codepen or jsfiddle?
I think that its the problem with mixed content.

**Comment by Varshazz** [comment]
Got it to work, was missing reference to the CSS
